SELECT E.*, D.DEPARTMENT_NAME
   FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
     ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
     
SELECT * FROM JOBS;

SELECT * FROM DEPARTMENTS;

SELECT distinct m.EMPLOYEE_ID as Manager_id, m.FIRST_NAME, m.last_NAME, m.job_id
  FROM EMPLOYEES e, EMPLOYEES m
 WHERE e.MANAGER_ID = m.EMPLOYEE_ID
 ORDER BY m.EMPLOYEE_ID;