SELECT E.*, D.DEPARTMENT_NAME
   FROM EMPLOYEES E INNER JOIN DEPARTMENTS D
     ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;
     
SELECT * FROM JOBS;

SELECT * FROM DEPARTMENTS;

SELECT distinct m.EMPLOYEE_ID as manager_id, m.FIRST_NAME, m.last_NAME, d.department_id
  FROM EMPLOYEES e, EMPLOYEES m, departments d
 WHERE e.MANAGER_ID = m.EMPLOYEE_ID
   and d.department_Id = e.department_id
 order by d.department_id;
 
 insert into employees
 value (?, ?, ?, ?, ?, sysdate, ?, ?, ?, ?, ?); 
 
 SELECT MAX(EMPLOYEE_ID) AS MAX_NO
   FROM EMPLOYEES;
   
DELETE from EMPLOYEES
 where employee_id = ?;
 
EXEC PROCEDURE_INSERT_FRIEND ('마이콜', '010-1234-1231', '쌍문동');
   
SELECT E.EMPLOYEE_ID,
       E.FIRST_NAME,
       E.LAST_NAME,
       E.EMAIL,
       E.PHONE_NUMBER,
       E.HIRE_DATE,
       E.JOB_ID,
       E.SALARY,
       E.COMMISSION_PCT,
       E.MANAGER_ID,
       E.DEPARTMENT_ID,
       D.DEPARTMENT_NAME 
  FROM EMPLOYEES E, DEPARTMENTS D 
 WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
   AND (LOWER(E.FIRST_NAME) LIKE '%st%' OR LOWER(E.LAST_NAME) LIKE '%st%')
   AND QUITDATE IS NULL
 ORDER BY E.EMPLOYEE_ID;

SELECT E.*, D.DEPARTMENT_NAME FROM EMPLOYEES E INNER JOIN DEPARTMENTS D ON E.DEPARTMENT_ID = D.DEPARTMENT_ID
WHERE quitdate is null
 ORDER BY E.EMPLOYEE_ID;

